# Generated by Django 5.1.4 on 2025-02-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField(max_length=3)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('correo', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
